# Generated by Django 3.2.13 on 2022-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
