# Generated by Django 3.2.13 on 2022-07-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_classsection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_teach',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_teaches',
            field=models.ManyToManyField(related_name='teachers', to='school.ClassSection'),
        ),
    ]
